--
-- Destruction of tables
--
DROP VIEW public.study_list;
DROP VIEW public.study_researcher_list;

DROP TABLE IF EXISTS public.protocol;

DROP TABLE IF EXISTS public.monitoring;

DROP TABLE IF EXISTS public.adverse_event;

DROP INDEX IF EXISTS public.visit_patient_idx;
DROP INDEX IF EXISTS public.visit_study_idx;
DROP TABLE IF EXISTS public.visit;

DROP INDEX IF EXISTS public.study_researcher_study_idx;
DROP TABLE IF EXISTS public.study_researcher;

DROP INDEX IF EXISTS public.researcher_number_idx;
DROP TABLE IF EXISTS public.researcher;

DROP INDEX IF EXISTS public.patient_study_idx;
DROP TABLE IF EXISTS public.patient;

DROP TABLE IF EXISTS public.study;

--
-- Table: public.study
--
CREATE TABLE IF NOT EXISTS public.study
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(128) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    sponsor character varying(128) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    start_date date NOT NULL DEFAULT now(),
    end_date date,
    protocol_visits integer NOT NULL DEFAULT 0,
    comments text COLLATE pg_catalog."default" DEFAULT ''::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT study_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.study
    OWNER to postgres;

GRANT ALL ON TABLE public.study TO anon;

GRANT ALL ON TABLE public.study TO authenticated;

GRANT ALL ON TABLE public.study TO postgres;

GRANT ALL ON TABLE public.study TO service_role;


--
-- Table: public.patient
--
CREATE TABLE IF NOT EXISTS public.patient
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint,
    "number" text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    start_date text COLLATE pg_catalog."default",
    exit_date text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    comments text COLLATE pg_catalog."default",
    CONSTRAINT patient_pkey PRIMARY KEY (id),
    CONSTRAINT patient_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.patient
    OWNER to postgres;

GRANT ALL ON TABLE public.patient TO anon;

GRANT ALL ON TABLE public.patient TO authenticated;

GRANT ALL ON TABLE public.patient TO postgres;

GRANT ALL ON TABLE public.patient TO service_role;

--
-- Index: patient_study_idx
--
CREATE INDEX IF NOT EXISTS patient_study_idx
    ON public.patient USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;


--
-- Table: public.researcher
--
CREATE TABLE IF NOT EXISTS public.researcher
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "number" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    name character varying(128) COLLATE pg_catalog."default",
    phone character varying(64) COLLATE pg_catalog."default",
    email character varying(128) COLLATE pg_catalog."default",
    comments text COLLATE pg_catalog."default",
    CONSTRAINT researcher_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.researcher
    OWNER to postgres;

GRANT ALL ON TABLE public.researcher TO anon;

GRANT ALL ON TABLE public.researcher TO authenticated;

GRANT ALL ON TABLE public.researcher TO postgres;

GRANT ALL ON TABLE public.researcher TO service_role;

--
-- Index: researcher_number_idx
--
CREATE INDEX IF NOT EXISTS researcher_number_idx
    ON public.researcher USING btree
    (number COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;


--
-- Table: public.study_researcher
--
CREATE TABLE IF NOT EXISTS public.study_researcher
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    researcher_id bigint NOT NULL,
    role character varying(64) COLLATE pg_catalog."default" NOT NULL,
    study_comments text COLLATE pg_catalog."default",
    CONSTRAINT study_researcher_pkey PRIMARY KEY (id),
    CONSTRAINT study_researcher_researcher_id_fkey FOREIGN KEY (researcher_id)
        REFERENCES public.researcher (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT study_researcher_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.study_researcher
    OWNER to postgres;

GRANT ALL ON TABLE public.study_researcher TO anon;

GRANT ALL ON TABLE public.study_researcher TO authenticated;

GRANT ALL ON TABLE public.study_researcher TO postgres;

GRANT ALL ON TABLE public.study_researcher TO service_role;

--
-- Index: study_researcher_study_idx
--
CREATE INDEX IF NOT EXISTS study_researcher_study_idx
    ON public.study_researcher USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;


--
-- Table: public.adverse_event
--
CREATE TABLE IF NOT EXISTS public.adverse_event
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id integer NOT NULL,
    patient_id bigint NOT NULL,
    event_date date NOT NULL,
    event_type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    CONSTRAINT event_pkey PRIMARY KEY (id),
    CONSTRAINT event_patient_id_fkey FOREIGN KEY (patient_id)
        REFERENCES public.patient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT event_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.adverse_event
    OWNER to postgres;

ALTER TABLE IF EXISTS public.adverse_event
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.adverse_event TO anon;

GRANT ALL ON TABLE public.adverse_event TO authenticated;

GRANT ALL ON TABLE public.adverse_event TO postgres;

GRANT ALL ON TABLE public.adverse_event TO service_role;

--
-- Table: public.visit
--
CREATE TABLE IF NOT EXISTS public.visit
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    visit_date date NOT NULL,
    visit_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    CONSTRAINT visit_pkey PRIMARY KEY (id),
    CONSTRAINT visit_patient_id_fkey FOREIGN KEY (patient_id)
        REFERENCES public.patient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT visit_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.visit
    OWNER to postgres;

GRANT ALL ON TABLE public.visit TO anon;

GRANT ALL ON TABLE public.visit TO authenticated;

GRANT ALL ON TABLE public.visit TO postgres;

GRANT ALL ON TABLE public.visit TO service_role;

--
-- Index: visit_patient_idx
--
CREATE INDEX IF NOT EXISTS visit_patient_idx
    ON public.visit USING btree
    (patient_id ASC NULLS LAST)
    TABLESPACE pg_default;
---
-- Index: visit_study_idx
--
CREATE INDEX IF NOT EXISTS visit_study_idx
    ON public.visit USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;


--
-- Table: public.protocol
--
CREATE TABLE IF NOT EXISTS public.protocol
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    event_date date NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT protocol_pkey PRIMARY KEY (id),
    CONSTRAINT protocol_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.protocol
    OWNER to postgres;

ALTER TABLE IF EXISTS public.protocol
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.protocol TO anon;

GRANT ALL ON TABLE public.protocol TO authenticated;

GRANT ALL ON TABLE public.protocol TO postgres;

GRANT ALL ON TABLE public.protocol TO service_role;


--
-- Table: public.monitoring
--
CREATE TABLE IF NOT EXISTS public.monitoring
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    meeting_date date NOT NULL,
    monitor character varying(128) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    CONSTRAINT monitoring_pkey PRIMARY KEY (id),
    CONSTRAINT monitoring_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.monitoring
    OWNER to postgres;

ALTER TABLE IF EXISTS public.monitoring
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.monitoring TO anon;

GRANT ALL ON TABLE public.monitoring TO authenticated;

GRANT ALL ON TABLE public.monitoring TO postgres;

GRANT ALL ON TABLE public.monitoring TO service_role;

--
-- View: public.study_list
--
CREATE OR REPLACE VIEW public.study_list
 AS
 SELECT id,
    name,
    sponsor,
    start_date,
    end_date,
    protocol_visits,
    comments,
    ( SELECT count(0) AS count
           FROM patient p
          WHERE p.study_id = s.id) AS patients,
    ( SELECT count(0) AS count
           FROM visit v
          WHERE v.study_id = s.id) AS visits,
    ( SELECT count(0) AS count
           FROM study_researcher sr
          WHERE sr.study_id = s.id) AS researchers,
    ( SELECT count(0) AS count
           FROM adverse_event ae
          WHERE ae.study_id = s.id) AS events
   FROM study s;

ALTER TABLE public.study_list
    OWNER TO postgres;

GRANT ALL ON TABLE public.study_list TO anon;
GRANT ALL ON TABLE public.study_list TO authenticated;
GRANT ALL ON TABLE public.study_list TO postgres;
GRANT ALL ON TABLE public.study_list TO service_role;


--
-- View: public.study_researcher_list
--
CREATE OR REPLACE VIEW public.study_researcher_list
 AS
 SELECT sr.id,
    sr.study_id,
    sr.researcher_id,
    sr.role,
    sr.study_comments,
    r.number,
    r.name,
    r.phone,
    r.email
   FROM study_researcher sr
     JOIN researcher r ON r.id = sr.researcher_id;

ALTER TABLE public.study_researcher_list
    OWNER TO postgres;

GRANT ALL ON TABLE public.study_researcher_list TO anon;
GRANT ALL ON TABLE public.study_researcher_list TO authenticated;
GRANT ALL ON TABLE public.study_researcher_list TO postgres;
GRANT ALL ON TABLE public.study_researcher_list TO service_role;

