services:
  app:
    image: zauberzeug/nicegui:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - ./app:/app # mounting local app directory
    working_dir: /app
    command: python3 main.py
