-------------------------------------------------
--
-- Table: public.user
--
CREATE TABLE IF NOT EXISTS public."user"
(
    user_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    pass_hash character varying(64) COLLATE pg_catalog."default" NOT NULL,
    user_role character varying(64) COLLATE pg_catalog."default" NOT NULL,
    change_pass boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,

    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_user_name_key UNIQUE (user_name)
)

TABLESPACE pg_default;

-- Index: index_user_pass
DROP INDEX IF EXISTS public.index_user_pass;

CREATE UNIQUE INDEX IF NOT EXISTS index_user_pass
    ON public."user" USING btree
    (user_name COLLATE pg_catalog."default" ASC NULLS LAST, pass_hash COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;


INSERT INTO public."user" (user_name, pass_hash, user_role, change_pass, created_by, updated_by)
VALUES ('admin', '299390b0010c72e591e83f0679d04a49304c9e40c31c4fc8ebad257f82db5ee8',
        'Admin', false, 'system', 'system');


-------------------------------------------------
--
-- Table: public.api_key
--
DROP TABLE IF EXISTS public.api_key;

CREATE TABLE IF NOT EXISTS public.api_key
(
    api_key_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	user_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    api_key character varying(128) COLLATE pg_catalog."default" NOT NULL,
    key_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
	key_description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    valid_until date NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT api_key_pkey PRIMARY KEY (api_key_id),
    CONSTRAINT api_key_unique UNIQUE (api_key)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.api_key
    OWNER to postgres;

-- Index: user_name_idx

DROP INDEX IF EXISTS public.user_name_idx;

CREATE INDEX IF NOT EXISTS user_name_idx
    ON public.api_key USING btree
    (user_name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;



-------------------------------------------------
--
-- Table: public.study
--
CREATE TABLE IF NOT EXISTS public.study
(
    study_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    protocol character varying(64) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    sponsor character varying(128) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL DEFAULT now(),
    end_date date,
    protocol_visits integer NOT NULL DEFAULT 0,
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT study_pkey PRIMARY KEY (study_id),
    CONSTRAINT study_name_key UNIQUE (name)
)

TABLESPACE pg_default;


-------------------------------------------------
--
-- Table: public.patient
--
CREATE TABLE IF NOT EXISTS public.patient
(
    patient_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint,
    "number" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    name character varying(128) COLLATE pg_catalog."default",
    start_date date NOT NULL DEFAULT now(),
    exit_date date,
    status text COLLATE pg_catalog."default",
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT patient_pkey PRIMARY KEY (patient_id),
    CONSTRAINT patient_number_key UNIQUE ("number"),
    CONSTRAINT patient_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (study_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-- Index: patient_study_idx

DROP INDEX IF EXISTS public.patient_study_idx;

CREATE INDEX IF NOT EXISTS patient_study_idx
    ON public.patient USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;


ALTER TABLE IF EXISTS public.patient DROP CONSTRAINT IF EXISTS number_study_unique;

ALTER TABLE IF EXISTS public.patient
    ADD CONSTRAINT number_study_unique UNIQUE (study_id, "number");


-------------------------------------------------
--
-- Table: public.researcher
--
CREATE TABLE IF NOT EXISTS public.researcher
(
    researcher_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "number" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    name character varying(128) COLLATE pg_catalog."default",
    phone character varying(64) COLLATE pg_catalog."default",
    email character varying(128) COLLATE pg_catalog."default",
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT researcher_pkey PRIMARY KEY (researcher_id)
)

TABLESPACE pg_default;

-- Index: researcher_number_idx

DROP INDEX IF EXISTS public.researcher_number_idx;

CREATE INDEX IF NOT EXISTS researcher_number_idx
    ON public.researcher USING btree
    (number COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;


-------------------------------------------------
--
-- Table: public.study_researcher
--
CREATE TABLE IF NOT EXISTS public.study_researcher
(
    sr_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    researcher_id bigint NOT NULL,
    role character varying(64) COLLATE pg_catalog."default" NOT NULL,
    study_comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT study_researcher_pkey PRIMARY KEY (sr_id),
    CONSTRAINT study_researcher_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (study_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT study_researcher_researcher_id_fkey FOREIGN KEY (researcher_id)
        REFERENCES public.researcher (researcher_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-- Index: study_researcher_study_idx

DROP INDEX IF EXISTS public.study_researcher_study_idx;

CREATE INDEX IF NOT EXISTS study_researcher_study_idx
    ON public.study_researcher USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;


-------------------------------------------------
--
-- Table: public.adverse_event
--
CREATE TABLE IF NOT EXISTS public.adverse_event
(
    adverse_event_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id integer NOT NULL,
    patient_id bigint NOT NULL,
    event_date date NOT NULL DEFAULT now(),
    event_type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT event_pkey PRIMARY KEY (adverse_event_id),
    CONSTRAINT event_patient_id_fkey FOREIGN KEY (patient_id)
        REFERENCES public.patient (patient_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT event_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (study_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-------------------------------------------------
--
-- Table: public.monitoring
--
CREATE TABLE IF NOT EXISTS public.monitoring
(
    monitoring_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    meeting_date date NOT NULL,
    monitor character varying(128) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT monitoring_pkey PRIMARY KEY (monitoring_id),
    CONSTRAINT monitoring_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (study_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-------------------------------------------------
--
-- Table: public.protocol
--
CREATE TABLE IF NOT EXISTS public.protocol
(
    protocol_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    event_date timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT protocol_pkey PRIMARY KEY (protocol_id),
    CONSTRAINT protocol_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (study_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-------------------------------------------------
--
-- Table: public.visit
--
CREATE TABLE IF NOT EXISTS public.visit
(
    visit_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    visit_date date NOT NULL DEFAULT now(),
    visit_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT visit_pkey PRIMARY KEY (visit_id),
    CONSTRAINT visit_patient_id_fkey FOREIGN KEY (patient_id)
        REFERENCES public.patient (patient_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT visit_study_id_fkey FOREIGN KEY (study_id)
        REFERENCES public.study (study_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-- Index: visit_patient_idx

DROP INDEX IF EXISTS public.visit_patient_idx;

CREATE INDEX IF NOT EXISTS visit_patient_idx
    ON public.visit USING btree
    (patient_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: visit_study_idx

DROP INDEX IF EXISTS public.visit_study_idx;

CREATE INDEX IF NOT EXISTS visit_study_idx
    ON public.visit USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;