-- Table: public.monitoring

-- DROP TABLE IF EXISTS public.monitoring;

CREATE TABLE IF NOT EXISTS public.monitoring
(
    monitoring_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    meeting_date date NOT NULL,
    monitor character varying(128) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT monitoring_pkey PRIMARY KEY (monitoring_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.monitoring
    OWNER to "creepy-aquamarine-tortoise";
