-- Table: public.patient

-- DROP TABLE IF EXISTS public.patient;

CREATE TABLE IF NOT EXISTS public.patient
(
    patient_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint,
    "number" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    name character varying(128) COLLATE pg_catalog."default",
    start_date date NOT NULL DEFAULT now(),
    exit_date date,
    status text COLLATE pg_catalog."default",
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT patient_pkey PRIMARY KEY (patient_id)
)

TABLESPACE pg_default;

-- ALTER TABLE IF EXISTS public.patient
--     OWNER to "creepy-aquamarine-tortoise";

-- Index: patient_study_idx

-- DROP INDEX IF EXISTS public.patient_study_idx;

CREATE INDEX IF NOT EXISTS patient_study_idx
    ON public.patient USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;