-- Table: public.protocol

-- DROP TABLE IF EXISTS public.protocol;

CREATE TABLE IF NOT EXISTS public.protocol
(
    protocol_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    event_date timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT protocol_pkey PRIMARY KEY (protocol_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.protocol
    OWNER to "creepy-aquamarine-tortoise";
