-- Table: public.study_researcher

-- DROP TABLE IF EXISTS public.study_researcher;

CREATE TABLE IF NOT EXISTS public.study_researcher
(
    sr_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    researcher_id bigint NOT NULL,
    role character varying(64) COLLATE pg_catalog."default" NOT NULL,
    study_comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT study_researcher_pkey PRIMARY KEY (sr_id)
)

TABLESPACE pg_default;

-- ALTER TABLE IF EXISTS public.study_researcher
--     OWNER to "creepy-aquamarine-tortoise";

-- Index: study_researcher_study_idx

-- DROP INDEX IF EXISTS public.study_researcher_study_idx;

CREATE INDEX IF NOT EXISTS study_researcher_study_idx
    ON public.study_researcher USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;