-- Table: public.visit

-- DROP TABLE IF EXISTS public.visit;

CREATE TABLE IF NOT EXISTS public.visit
(
    visit_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    study_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    visit_date date NOT NULL DEFAULT now(),
    visit_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    comments text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT visit_pkey PRIMARY KEY (visit_id),
    CONSTRAINT visit_patient_id_fkey FOREIGN KEY (patient_id)
        REFERENCES public.patient (patient_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.visit
    OWNER to "creepy-aquamarine-tortoise";

-- Index: visit_patient_idx

-- DROP INDEX IF EXISTS public.visit_patient_idx;

CREATE INDEX IF NOT EXISTS visit_patient_idx
    ON public.visit USING btree
    (patient_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: visit_study_idx

-- DROP INDEX IF EXISTS public.visit_study_idx;

CREATE INDEX IF NOT EXISTS visit_study_idx
    ON public.visit USING btree
    (study_id ASC NULLS LAST)
    TABLESPACE pg_default;